name: Pull request to master branch
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      UI_APP_E2E_PROJECT: client-e2e
      UI_APP_E2E_TARGET_HOST: https://d0m2tqifnk.execute-api.us-east-2.amazonaws.com/
    steps:
      - uses: actions/checkout@v2
 
      - name: Check var
        shell: bash
        run: git rev-parse ${remote/origin/master}
        
      - name: Check var 2
        shell: bash
        run: git rev-parse ${GITHUB_SHA}

      - name: Retreive last test sha
        id: last-test-sha
        run: echo "::set-output name=sha::$(git rev-parse ${GITHUB_SHA})"
