name: Pull request to master branch
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code with lint and unit tests
    steps:
      - uses: actions/checkout@v2
 
      - run: git fetch origin master
        
      - name: Install dependencies
        run: npm install

      - name: Run affected tests
        run: npm run affected:lint -- --base=$(git rev-parse origin/master~1)

      - name: Run affected tests
        run: npm run affected:test -- --base=$(git rev-parse origin/master~1)
