name: PR to master

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [15.x]

    # Define Steps
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install environment
        run: |
          rm -rf node_modules && rm -rf dist && rm -rf docs && rm -rf coverage
          npm ci
      - name: Run lint
        run: ./.github/scripts/lint.sh False

      - name: Tests coverage
        run: ./.github/scripts/test.sh False True