name: Pull request to master branch
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code with lint and unit tests
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      UI_APP_E2E_PROJECT: client-e2e
      UI_APP_E2E_TARGET_HOST: https://d0m2tqifnk.execute-api.us-east-2.amazonaws.com/
    steps:
      - uses: actions/checkout@v2
 
      - run: git fetch origin master
      
      - run: git rev-parse origin/master
      
      - name: Install dependencies
        run: npm install

      - name: Run affected tests
        run: npm run affected:lint --base=$(git rev-parse origin/master) --head=$(git rev-parse ${GITHUB_SHA})

      - name: Run affected tests
        run: npm run affected:test --base=$(git rev-parse origin/master) --head=(git rev-parse ${GITHUB_SHA})
