name: Pull request to master branch
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      UI_APP_E2E_PROJECT: client-e2e
      UI_APP_E2E_TARGET_HOST: https://d0m2tqifnk.execute-api.us-east-2.amazonaws.com/
    steps:
      - uses: actions/checkout@v2
 
      - run: git fetch --no-tags --prune --depth=5 origin master
 
      - name: Install dependencies
        run: npm install

      - name: Run affected tests
        run: npm run affected:lint --base=origin/master

      - name: Run affected tests
        run: npm run affected:test --base=origin/master
